---
- hosts: all
  become: yes
  gather_facts: yes

  pre_tasks:
    - name: Ensure Ansible dependencies are installed (CentOS 6).
      yum:
        name: libselinux-python
        state: present
      when: ansible_distribution_major_version | int == 6

  roles:
    - geerlingguy.nfs
    - geerlingguy.packer_rhel
